const fs = require('fs');
const path = require('path');

// Uploaded files (documents, avatars, receipts) live in a private Cloudflare R2
// bucket when R2 credentials are configured. Render's disk is wiped on every
// deploy/restart, so production must use R2. Without credentials (local dev),
// files fall back to server/uploads/<folder> on disk.
const {
  R2_ACCOUNT_ID,
  R2_ACCESS_KEY_ID,
  R2_SECRET_ACCESS_KEY,
  R2_BUCKET,
} = process.env;

const useR2 = Boolean(R2_ACCOUNT_ID && R2_ACCESS_KEY_ID && R2_SECRET_ACCESS_KEY && R2_BUCKET);

const LOCAL_ROOT = process.env.UPLOAD_ROOT || path.resolve(__dirname, '../../uploads');

let s3 = null;
let S3Commands = null;
if (useR2) {
  const { S3Client, PutObjectCommand, GetObjectCommand, DeleteObjectCommand } = require('@aws-sdk/client-s3');
  s3 = new S3Client({
    region: 'auto',
    endpoint: `https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com`,
    credentials: { accessKeyId: R2_ACCESS_KEY_ID, secretAccessKey: R2_SECRET_ACCESS_KEY },
  });
  S3Commands = { PutObjectCommand, GetObjectCommand, DeleteObjectCommand };
  console.log(`🗄️  File storage: Cloudflare R2 (bucket "${R2_BUCKET}")`);
} else {
  console.warn(`🗄️  File storage: local disk (${LOCAL_ROOT}) — files will NOT survive a Render redeploy.`);
  console.warn('    Set R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY and R2_BUCKET to use R2.');
}

// Stored names are generated by us, but guard against path tricks anyway.
const safeName = (name) => path.basename(String(name));
const objectKey = (folder, name) => `${folder}/${safeName(name)}`;
const localPath = (folder, name) => path.join(LOCAL_ROOT, folder, safeName(name));

const saveFile = async (folder, name, buffer, contentType) => {
  if (useR2) {
    await s3.send(
      new S3Commands.PutObjectCommand({
        Bucket: R2_BUCKET,
        Key: objectKey(folder, name),
        Body: buffer,
        ContentType: contentType,
      })
    );
    return;
  }
  const target = localPath(folder, name);
  await fs.promises.mkdir(path.dirname(target), { recursive: true });
  await fs.promises.writeFile(target, buffer);
};

// Deleting a file that is already gone is not an error.
const deleteFile = async (folder, name) => {
  if (!name) return;
  try {
    if (useR2) {
      await s3.send(new S3Commands.DeleteObjectCommand({ Bucket: R2_BUCKET, Key: objectKey(folder, name) }));
    } else {
      await fs.promises.unlink(localPath(folder, name));
    }
  } catch (err) {
    if (err.code !== 'ENOENT') console.error(`Failed to remove stored file ${folder}/${name}: ${err.message}`);
  }
};

/**
 * Streams a stored file into the response. Returns false (without touching the
 * response) when the file does not exist, so the caller can send its own 404.
 * `downloadName` sets an attachment filename; omit it to serve inline.
 */
const sendStoredFile = async (res, folder, name, { contentType, downloadName, cacheSeconds } = {}) => {
  let body;
  let length;

  if (useR2) {
    try {
      const obj = await s3.send(new S3Commands.GetObjectCommand({ Bucket: R2_BUCKET, Key: objectKey(folder, name) }));
      body = obj.Body;
      length = obj.ContentLength;
      contentType = contentType || obj.ContentType;
    } catch (err) {
      if (err.name === 'NoSuchKey' || err.$metadata?.httpStatusCode === 404) return false;
      throw err;
    }
  } else {
    const file = localPath(folder, name);
    try {
      length = (await fs.promises.stat(file)).size;
    } catch (err) {
      if (err.code === 'ENOENT') return false;
      throw err;
    }
    body = fs.createReadStream(file);
  }

  if (contentType) res.setHeader('Content-Type', contentType);
  else res.type(path.extname(safeName(name)) || 'application/octet-stream');
  if (length) res.setHeader('Content-Length', length);
  if (downloadName) res.attachment(downloadName);
  if (cacheSeconds) res.setHeader('Cache-Control', `private, max-age=${cacheSeconds}`);

  await new Promise((resolve, reject) => {
    body.on('error', reject);
    res.on('finish', resolve);
    res.on('close', resolve);
    body.pipe(res);
  });
  return true;
};

module.exports = { saveFile, deleteFile, sendStoredFile, usingR2: useR2 };
